# coding: utf-8

"""
    fcd-endpoint-client

    FCD-endpoint-client  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@be-mobile.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.fcd_metadata import FcdMetadata  # noqa: E501
from openapi_client.rest import ApiException


class TestFcdMetadata(unittest.TestCase):
    """FcdMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFcdMetadata(self):
        """Test FcdMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.fcd_metadata.FcdMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
