/*
 * fcd-endpoint-client
 *
 * FCD-endpoint-client
 *
 * API version: 1.0.0
 * Contact: api-support@be-mobile.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Fcd FCD-data
type Fcd struct {
	VehicleId string `json:"vehicleId"`
	VehicleType float32 `json:"vehicleType"`
	Timestamp float32 `json:"timestamp"`
	Lon float32 `json:"lon"`
	Lat float32 `json:"lat"`
	Heading float32 `json:"heading"`
	Speed float32 `json:"speed"`
	Hdop float32 `json:"hdop"`
	Metadata FcdMetadata `json:"metadata"`
}
