/*
 * fcd-endpoint-client
 *
 * FCD-endpoint-client
 *
 * API version: 1.0.0
 * Contact: api-support@be-mobile.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// FcdMetadata struct for FcdMetadata
type FcdMetadata struct {
	RouteNumber float32 `json:"routeNumber"`
}
