# coding: utf-8

# flake8: noqa
"""
    fcd-endpoint-client

    FCD-endpoint-client  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@be-mobile.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.fcd import Fcd
from openapi_client.models.fcd_metadata import FcdMetadata
