# coding: utf-8

"""
    fcd-endpoint-client

    FCD-endpoint-client  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@be-mobile.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class FcdMetadata(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'route_number': 'float'
    }

    attribute_map = {
        'route_number': 'routeNumber'
    }

    def __init__(self, route_number=None, local_vars_configuration=None):  # noqa: E501
        """FcdMetadata - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._route_number = None
        self.discriminator = None

        self.route_number = route_number

    @property
    def route_number(self):
        """Gets the route_number of this FcdMetadata.  # noqa: E501


        :return: The route_number of this FcdMetadata.  # noqa: E501
        :rtype: float
        """
        return self._route_number

    @route_number.setter
    def route_number(self, route_number):
        """Sets the route_number of this FcdMetadata.


        :param route_number: The route_number of this FcdMetadata.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and route_number is None:  # noqa: E501
            raise ValueError("Invalid value for `route_number`, must not be `None`")  # noqa: E501

        self._route_number = route_number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FcdMetadata):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FcdMetadata):
            return True

        return self.to_dict() != other.to_dict()
