/* 
 * fcd-endpoint-client
 *
 * FCD-endpoint-client
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@be-mobile.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// FcdMetadata
    /// </summary>
    [DataContract]
    public partial class FcdMetadata :  IEquatable<FcdMetadata>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FcdMetadata" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FcdMetadata() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FcdMetadata" /> class.
        /// </summary>
        /// <param name="routeNumber">routeNumber (required).</param>
        public FcdMetadata(decimal routeNumber = default(decimal))
        {
            // to ensure "routeNumber" is required (not null)
            if (routeNumber == null)
            {
                throw new InvalidDataException("routeNumber is a required property for FcdMetadata and cannot be null");
            }
            else
            {
                this.RouteNumber = routeNumber;
            }
            
        }
        
        /// <summary>
        /// Gets or Sets RouteNumber
        /// </summary>
        [DataMember(Name="routeNumber", EmitDefaultValue=false)]
        public decimal RouteNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FcdMetadata {\n");
            sb.Append("  RouteNumber: ").Append(RouteNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FcdMetadata);
        }

        /// <summary>
        /// Returns true if FcdMetadata instances are equal
        /// </summary>
        /// <param name="input">Instance of FcdMetadata to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FcdMetadata input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RouteNumber == input.RouteNumber ||
                    (this.RouteNumber != null &&
                    this.RouteNumber.Equals(input.RouteNumber))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RouteNumber != null)
                    hashCode = hashCode * 59 + this.RouteNumber.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
