# coding: utf-8

"""
    fcd-endpoint-client

    FCD-endpoint-client  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@be-mobile.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_ws(self):
        """Test case for get_ws

        websocket to push fcd data to  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
