/* 
 * fcd-endpoint-client
 *
 * FCD-endpoint-client
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@be-mobile.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing FcdMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FcdMetadataTests
    {
        // TODO uncomment below to declare an instance variable for FcdMetadata
        //private FcdMetadata instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FcdMetadata
            //instance = new FcdMetadata();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FcdMetadata
        /// </summary>
        [Test]
        public void FcdMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" FcdMetadata
            //Assert.IsInstanceOf(typeof(FcdMetadata), instance);
        }


        /// <summary>
        /// Test the property 'RouteNumber'
        /// </summary>
        [Test]
        public void RouteNumberTest()
        {
            // TODO unit test for the property 'RouteNumber'
        }

    }

}
