/* 
 * fcd-endpoint-client
 *
 * FCD-endpoint-client
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@be-mobile.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Fcd
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FcdTests
    {
        // TODO uncomment below to declare an instance variable for Fcd
        //private Fcd instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Fcd
            //instance = new Fcd();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Fcd
        /// </summary>
        [Test]
        public void FcdInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Fcd
            //Assert.IsInstanceOf(typeof(Fcd), instance);
        }


        /// <summary>
        /// Test the property 'VehicleId'
        /// </summary>
        [Test]
        public void VehicleIdTest()
        {
            // TODO unit test for the property 'VehicleId'
        }
        /// <summary>
        /// Test the property 'VehicleType'
        /// </summary>
        [Test]
        public void VehicleTypeTest()
        {
            // TODO unit test for the property 'VehicleType'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Lon'
        /// </summary>
        [Test]
        public void LonTest()
        {
            // TODO unit test for the property 'Lon'
        }
        /// <summary>
        /// Test the property 'Lat'
        /// </summary>
        [Test]
        public void LatTest()
        {
            // TODO unit test for the property 'Lat'
        }
        /// <summary>
        /// Test the property 'Heading'
        /// </summary>
        [Test]
        public void HeadingTest()
        {
            // TODO unit test for the property 'Heading'
        }
        /// <summary>
        /// Test the property 'Speed'
        /// </summary>
        [Test]
        public void SpeedTest()
        {
            // TODO unit test for the property 'Speed'
        }
        /// <summary>
        /// Test the property 'Hdop'
        /// </summary>
        [Test]
        public void HdopTest()
        {
            // TODO unit test for the property 'Hdop'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
