openapi: 3.0.0
info:
  title: fcd-endpoint-client
  version: 1.0.0
  description: FCD-endpoint-client
  contact:
    name: Be-Mobile API Support
    email: api-support@be-mobile.com
  x-audience: external-partner
  x-business-domain: data
servers:
  - url: 'wss://provider-fcd.bemobile.biz'
paths:
  /ws:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      operationId: get-ws
      description: used to push gps-positions to endpoint
      x-internal: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GPSPosition'
        description: ''
      parameters: []
    parameters: []
components:
  schemas:
    GPSPosition:
      description: GPS Position
      type: object
      x-examples:
        example:
          vehicleId: ASCII-Vehicle-ID
          vehicleType: 1
          engineState: 0
          timestamp: 1479673407
          lon: 51.019426
          lat: 3.768572
          heading: 270
          hdop: 5
          speed: 120.5
          metadata:
            routeNumber: 62
      title: ''
      properties:
        vehicleId:
          type: string
        vehicleType:
          type: integer
        engineState:
          type: integer
        timestamp:
          type: integer
        lon:
          type: number
        lat:
          type: number
        heading:
          type: number
        hdop:
          type: number
        speed:
          type: number
        metadata:
          type: object
      required:
        - vehicleId
        - vehicleType
        - engineState
        - timestamp
        - lon
        - lat
        - heading
        - hdop
        - speed
        - metadata
  securitySchemes: {}
