openapi: 3.0.0
info:
  title: fcd-endpoint-client
  version: 1.0.0
  description: FCD-endpoint-client
  contact:
    name: Be-Mobile API Support
    email: api-support@be-mobile.com
  x-audience: external-partner
  x-business-domain: data
servers:
  - url: 'wss://provider-fcd.bemobile.biz'
paths:
  /wss:
    get:
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      operationId: get-ws
      description: '!!! Not an actual get request !!! The connection to the server needs to be a websocket. This is used to send a GPS position to an endpoint'
      x-internal: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GPSPosition'
        description: ''
      parameters: []
    parameters: []
components:
  schemas:
    GPSPosition:
      description: GPS Position
      type: object
      x-examples:
        example:
          vehicleId: ASCII-Vehicle-ID
          vehicleType: 1
          engineState: 0
          timestamp: 1479673407
          lon: 51.019426
          lat: 3.768572
          heading: 270
          hdop: 5
          speed: 120.5
          metadata:
            routeNumber: 62
      title: ''
      properties:
        vehicleId:
          type: string
          example: 'ASCII-Vehicle-ID'
          description: 'Vehicle or FCD provider vehicle session ID (max 64 bytes)'
        vehicleType:
          type: integer
          example: '1'
          description: 'Vehicle type'
        engineState:
          type: integer
          example: '1'
          description: |
            '-1: unknown
            0: off
            1: on'
        timestamp:
          type: integer
          example: '1479673407'
          description: 'Unix Epoch timestamp in milliseconds (i.e. number of milliseconds since Jan 01 1970 (UTC))'
        lon:
          type: number
          format: float
          example: '51.019426'
          description: 'Longitude'
        lat:
          type: number
          format: float
          example: '3.768572'
          description: 'Latitude'
        heading:
          type: number
          format: float
          example: '270'
          description: 'Heading relative to north (0 degrees), range 0 - 359'
        hdop:
          type: number
          format: float
          example: '5'
          description: 'Accuracy in meters'
        speed:
          type: number
          format: float
          example: '120.5'
          description: 'Speed in kilometers per hour'
        metadata:
          type: object
          description: 'Supplier specific information'
      required:
        - vehicleId
        - vehicleType
        - engineState
        - timestamp
        - lon
        - lat
        - heading
        - hdop
        - speed
        - metadata
  securitySchemes: {}
